apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tce-workshops
spec:
  analytics:
    webhook:
      url: https://tanzu-dev-portal.netlify.app/developer/workshop-status?token=iFxXtF9Max9FTzasoCFboJ
  portal:
    sessions:
      maximum: 200
    reserved: 20
  workshops:
  - name: tce-dev-guide
    expires: 20m
    orphaned: 5m
  - name: tce-package-guide
    expires: 20m
    orphaned: 5m
  
