apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tce-package-guide
spec:
  title: Tanzu Community Edition Package Management Guide
  description: Learn how Tanzu Community Edition can help you istall addons/packages
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.dev/Boskey/tce-package-guide
  content:
    image: ghcr.io/boskey/tce-educates:latest
    files: github.com/boskey/tce-package-guide
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)    