apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tce-package-guide
spec:
  title: Tanzu Community Edition Package Management Guide
  description: Learn how Tanzu Community Edition can help you istall addons/packages
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.dev/Boskey/tce-package-guide
  content:
    image: ghcr.io/boskey/tce-educates:latest
    files: github.com/boskey/tce-package-guide
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-tanzu-addons-manager
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: tanzu-addons-manager-clusterrole
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1 
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-tanzu-capabilities-manager
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: tanzu-capabilities-manager-clusterrole
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account) 
    - apiVersion: rbac.authorization.k8s.io/v1 
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-data-packagemanager-carvel
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name:  $(workshop_namespace)-data-packagemanager-carvel
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    - apiVersion: rbac.authorization.k8s.io/v1 
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-monitorns-view
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name:  $(workshop_namespace)-monitorns-view
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)         
  environment:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-data-packagemanager-carvel
      rules:
        - apiGroups:
            - data.packaging.carvel.dev
          resources:
            - packagemetadatas
          verbs:
            - get
            - list
            - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(workshop_namespace)-monitorns-view
      rules:
        - apiGroups:
            - ""
          resources:
            - pods
          verbs:
            - get
            - list
            - watch